---
title: "DATA 534 Individual Project Notebook"
author: "Rachel Kamphuis"
date: "2026-01-20"
output: pdf_document
---

## 2026-01-19

### Summary

-   Met with group members to decide on a topic for our project
-   Decided on The Metropolitan Museum of Art Collection API
-   Read the API's documentation <https://metmuseum.github.io/>

### Contribution to Project

-   Decided on our topic
-   Created Project Report github page and notebook.Rmd file

### Links to Github

-   <https://github.com/rmkamphuis/DATA_534_Project_Notebook/commit/20bd1c93da37cf02c40d933c2fa9fabf45d0738d>

## 2026-01-20

### Summary

- Made proposal PowerPoint
- Proofread and edited Gladys's rough draft proposal word document
- Proofread and accepted Gladys's PR

### Contribution to Project

- Designed our proposal PowerPoint

### Links to Github

- N/A

## 2026-01-26

### Summary

- Finalized group member roles/contributions (split work into 3 sections)

### Contribution to Project

- Each member now has a defined role

### Links to Github

- N/A

## 2026-01-27

### Summary

- Reviewed contribution document, started planning my part (part B), and began met_object() file

### Contribution to Project

- Made notes of how to start the code for part B and began the met_object() file

### Links to Github

- N/A

## 2026-01-28

### Summary

- Wrote the entirety of the met_objects() and met_tidy_object() files and finished the met_object file

### Contribution to Project

- Wrote the met_object(), met_objects(), and met_tidy_object() files

### Links to Github
- https://github.com/ChoWingDev/Data534_Museum_of_Art_API/pull/4

## 2026-02-01

### Summary

- Created our final presentation PowerPoint and sent it to group members for review
- Altered Kara's vignette to include installation information

### Contribution to Project

- Made our PowerPoint for our presentation
- Improved vignette

### Links to Github
- https://github.com/ChoWingDev/Data534_Museum_of_Art_API/pull/10

## 2026-02-02

### Summary

- Fixed the error I created yesterday while adding to Kara's vignette (Actions were failing)
- Passed in the project

### Contribution to Project

- Fixed my error 

### Links to Github
- https://github.com/ChoWingDev/Data534_Museum_of_Art_API/pull/10
